name: Deploy Zendesk App to Dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - name: Add ZAT Config
        env:
          ZAT_DEV: ${{ secrets.ZAT_DEV }}
        run: |
          echo $ZAT_DEV >> .zat
          echo `pwd`

      - name: My Test
        run: |
          echo `pwd`
          
      - name: ZAT Deploy
        uses: zendesk/zat-deploy@master
