name: Deploy Zendesk App to UAT

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - name: Add ZAT Config
        env:
          ZAT_UAT: ${{ secrets.ZAT_UAT }}
        run: |
          echo $ZAT_UAT >> .zat

      - name: ZAT Deploy
        uses: zendesk/zat-deploy@master
